### ISSUE TITLE
Cannot connect to docker-electroneumd running on Synology Diskstation

### ISSUE THREAD

**Issue by UdoK** [jc21/docker-electroneumd#1]
I'm running docker-electroneumd on my Synology Diskstation. It synced the blockchain completly.
If I want now to connect from my MAC with ./electroneum-wallet-cli --daemon-address 192.168.2.22:26968 --wallet-file xxx.etn to the electroneumd on the Diskstation then I get this error:

Error: wallet failed to connect to daemon: http://192.168.2.22:26968. Daemon either is not started or wrong port was passed. Please make sure daemon is running or restart the wallet with the correct daemon address.

Any idea what can be the problem?

**Comment by jc21** [comment]
I'm not familiar with Synology Diskstation however you'll need to open the ports for your docker container. If you're using vanilla docker command:

```bash
docker run --detach \
    --name electroneumd \
    -p 26967:26967 \
    -p 26968:26968 \
    -v /path/to/blockchain:/root/.electroneum \
    -v /path/to/wallet:/wallet \
    jc21/electroneumd
```

or if using docker-compose:

```yml
version: "2"
services:
  app:
    image: jc21/electroneumd
    ports:
      - 26967:26967
      - 26968:26968
    volumes:
      - "./data/node:/root/.electroneum"
      - "./data/wallet:/wallet"
```

Additionally, when the container is running, you can run the wallet command on that container:

```bash
docker exec -ti electroneumd /bin/bash -c 'cd /wallet && electroneum-wallet-cli'
```

or

```bash
docker-compose exec app /bin/bash -c 'cd /wallet && electroneum-wallet-cli'
```
